CREATE TABLE customer_behavior (
    customer_id INT,
    age INT,
    gender VARCHAR(10),
    item_purchased VARCHAR(50),
    category VARCHAR(50),
    purchase_amount INT,
    location VARCHAR(100),
    size VARCHAR(10),
    color VARCHAR(30),
    season VARCHAR(20),
    review_rating FLOAT,
    subscription_status VARCHAR(10),
    shipping_type VARCHAR(50),
    discount_applied VARCHAR(10),
    previous_purchases INT,
    payment_method VARCHAR(50),
    frequency_of_purchases VARCHAR(30),
    age_group VARCHAR(20),
    purchase_frequency_days INT
);

select * from customer_behavior
limit 10;

--total revenue generated by male vs. female customers
SELECT 
    gender, 
    SUM(purchase_amount) AS total_revenue
FROM customer_behavior
GROUP BY gender;

--  customers who used a discount AND spent above the overall average purchase value
SELECT 
    customer_id, 
    purchase_amount
FROM customer_behavior
WHERE discount_applied = 'Yes'
  AND purchase_amount > (SELECT AVG(purchase_amount) FROM customer_behavior);

--top 5 products with the highest average review ratings
SELECT 
    item_purchased, 
    ROUND(AVG(review_rating::NUMERIC), 2) AS avg_review_rating
FROM customer_behavior
GROUP BY item_purchased
ORDER BY avg_review_rating DESC
LIMIT 5;

-- Compare average purchase amount between Standard and Express shipping options
SELECT 
    shipping_type, 
    ROUND(AVG(purchase_amount), 2) AS avg_purchase_amount
FROM customer_behavior
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

-- Analyze whether subscribed customers spend more than non-subscribed ones
SELECT 
    subscription_status,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(purchase_amount), 2) AS average_spend,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer_behavior
GROUP BY subscription_status
ORDER BY total_revenue DESC, average_spend DESC;

-- top 5 products with the highest percentage of discounted purchases
SELECT 
    item_purchased,
    ROUND(
        100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 
        2
    ) AS discount_percentage
FROM customer_behavior
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;

-- Segment customers as New, Returning, or Loyal based on their previous purchase history
WITH segmented_customers AS (
    SELECT 
        customer_id, 
        previous_purchases,
        CASE 
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS segment
    FROM customer_behavior
)
SELECT 
    segment AS customer_segment,
    COUNT(*) AS total_customers
FROM segmented_customers
GROUP BY segment
ORDER BY total_customers DESC;

--  Retrieve the top 3 most frequently purchased items in each category
WITH ranked_items AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS rank_in_category
    FROM customer_behavior
    GROUP BY category, item_purchased
)
SELECT 
    category, 
    item_purchased, 
    total_orders, 
    rank_in_category
FROM ranked_items
WHERE rank_in_category <= 3;

--  Check if repeat buyers (more than 5 previous purchases) are more likely to be subscribers
SELECT 
    subscription_status,
    COUNT(customer_id) AS repeat_buyer_count
FROM customer_behavior
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Calculating total revenue contribution by each age group
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer_behavior
GROUP BY age_group
ORDER BY total_revenue DESC;




